# Generated by Django 3.2.6 on 2022-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_auto_20220113_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='close_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opens_at',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.JSONField(default=' '),
            preserve_default=False,
        ),
    ]
